create table security_user(
id bigint generated by default as identity,
username varchar(255),
password varchar(255),
email varchar(255),
role varchar(255),
createDate datetime(8),
primary key (id)
)