drop table if exists security_user CASCADE;
create table security_user(
id bigint generated by default as identity,
username varchar(255),
password varchar(255),
email varchar(255),
role varchar(255),
create_date datetime(8),
primary key (id)
)
update security_user set role='ROLE_MANAGER' where username='manager';
update security_user set role='ROLE_ADMIN' where username='admin';